spring:
  application:
    name: chat_app_server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatapp
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, update, validate, none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
  web:
    cors:
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  ai:
    openai:
      api-key: PhuocTD
jwt:
  secret: 3Vlc3Mgc29tZSB2ZXJ5IHZlcnkgbG9uZyByYW5kb20gc2VjcmV0IHZhbHVlIQ==
  expiration: 86400000 # Thời gian hết hạn của token (milliseconds)

TOKEN_EXPIRED: 2592000
TOKEN_SECRET: chatapp
